[Interface]
Address = 192.0.2.250/32
PrivateKey = EXAMPLE_PRIVATE_KEY_REPLACE_ME
Jc = 4
Jmin = 40
Jmax = 70
S1 = 0
S2 = 0
H1 = 1
H2 = 2
H3 = 3
H4 = 4
[Peer]
PublicKey = EXAMPLE_PUBLIC_KEY_REPLACE_ME
PresharedKey = EXAMPLE_PRESHARED_KEY_REPLACE_ME
AllowedIPs = 192.0.2.1/32
Endpoint = vpn.example.org:51820
PersistentKeepalive = 25
